### ISSUE TITLE
/bt tabcomplete kick

### ISSUE THREAD

**Issue by Rickleuf** [BuildTheEarth/bte-net-issues#14]
**Describe the bug**
When typing in /bt and then pressing tab to get a list of all buildteam servers you can do the /bt command with, sometimes you get kicked with a very long message.

**To Reproduce**
1. open chat
2. type /bt
3. press tab

**Expected behavior**
When typing /bt and pressing tab you get a autocomplete list with all available options to autocomplete.

**Screenshots**
[Screenshot of the error message](https://cdn.discordapp.com/attachments/785145395155566622/795384036544872458/unknown.png)

**Minecraft Version:**
 - Java
 - 1.12.2 (modpack)
 
**Additional context**
I can't reproduce this on 1.16.3 (vanilla)

**Comment by MineFact** [comment]
This is probably a build team or a client problem.
