### ISSUE TITLE
Remove MineFact information from the bottom text in the tab (etc "Build 10 buildings to get Builder")

### ISSUE THREAD

**Issue by TerraShy** [BuildTheEarth/bte-net-issues#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Minecraft Version:**
 - Bedrock or Java
 - Minecraft Version (Ex: 1.12.2)

**Additional context**

**Comment by Nudelsuppe42** [comment]
Please read the other issues first. This is doubled
