### ISSUE TITLE
Bedrock issues in build teams

### ISSUE THREAD

**Issue by MrBobert59** [BuildTheEarth/bte-net-issues#19]
Submission by IΛη#9360

**Describe the bug**
basically when you join the server with bedrock some chunks load, but all other chunks dont. The only way to load these buggy chunks is to go to the location that is not loading and then leave and join the server again, but the chunks you loaded the other time wont load

**To Reproduce**
Join the Brazilian servers with bedrock 

**Expected behavior**
bobert - just make it not buggy 

**Screenshots**
![imgur](https://user-images.githubusercontent.com/76740487/105097742-1f706600-5a77-11eb-9b18-d2d4ac935c6e.png)

**Minecraft Version:**
 Bedrock

**Additional context**
It worked fine on bbn

**Comment by MineFact** [comment]
We are not the author of Geyser (The ones who make Bedrock playable on Java servers) so we cant fix it. I can try to update Geyser to the latest version but I cant guarantee anything.

**Comment by XboxBedrock** [comment]
Ive tried numerous mohist versions and everything ive tried yields the same results

**Comment by yyrichy** [comment]
what result

**Comment by XboxBedrock** [comment]
buggy chunk loading, with like terrain skeletons in a way

**Comment by yyrichy** [comment]
yeah just /hub and /bt <name> a few times, with pauses in between.

**Comment by XboxBedrock** [comment]
![image](https://user-images.githubusercontent.com/68715625/105417358-59b14300-5bf0-11eb-97c8-2ceb96cce051.png)
does this, seemingly leaves some ghost chunks of the lobby too

**Comment by yyrichy** [comment]
Yeah I know, don't think there's a fix though

**Comment by MineFact** [comment]
as I said we are not the authors of those tools, so we cant fix them
