### ISSUE TITLE
Global chat

### ISSUE THREAD

**Issue by CraftOre** [BuildTheEarth/bte-net-issues#20]
**Is your feature request related to a problem? Please describe.**
Add a list of things that won't be send to global chat if typed or change the prefix. Many people type something like '._.' and it gets sent there, and that's annoying.

**Describe the solution you'd like**
Above.

**Additional context**
No more context needed.

**Comment by Nudelsuppe42** [comment]
The prefix has been updated to **!**, so this shouldnt be a problem.
