### ISSUE TITLE
Server crash bug

### ISSUE THREAD

**Issue by Thingoo** [BuildTheEarth/bte-net-issues#22]
**Describe the bug**
loading new chunks will create the server to crash this is by using tpll or just loading chucks that havnt been loaded
**To Reproduce**
join hub.bteoce.com then join /server qld  and tpll to somwhere in queensland and server will crash 
**Expected behavior**
go to the area and it work 
**Screenshots**

**Minecraft Version:**
 - Minecraft Version (Ex: 1.12.2)

**Additional context**
server starts fine and can play in area that are loaded fine just the new chunks weird 
this is console log from when it crashes
[console qld.txt](https://github.com/BuildTheEarth/bte-net-issues/files/5887351/console.qld.txt)
hopfully the console log will help but it says 

Failed to get tree cover data 8140 2881 : java.io.IOException: Server returned HTTP response code: 408 for URL: https://gis-treecover.wri.org/arcgis/rest/services/TreeCover2000/ImageServer/exportImage?f=image&bbox=153.4144,-28.00576000000001,153.45536000000004,-28.046720000000008&imageSR=4152&bboxSR=4152&format=tiff&adjustAspectRatio=false&&interpolation=RSP_CubicConvolution&size=256,256

mhttps://gis-treecover.wri.org/arcgis/rest/services/TreeCover2000/ImageServer/exportImage?f=image&bbox=153.4144,-28.00576000000001,153.45536000000004,-28.046720000000008&imageSR=4152&bboxSR=4152&format=tiff&adjustAspectRatio=false&&interpolation=RSP_CubicConvolution&size=256,256

The server has stopped responding!

then a bunch or error messages

**Comment by noahhusby** [comment]
Is this related to the buildtheearth.net network? If not, then please message the BTE Support Bot

**Comment by Thingoo** [comment]
> Is this related to the buildtheearth.net network? If not, then please message the BTE Support Bot

not direcly so ill message that bot then
