### ISSUE TITLE
Build Team Command should not reconnect you to the same server.

### ISSUE THREAD

**Issue by Coppertine** [BuildTheEarth/bte-net-issues#23]
**Describe the bug**
The build team command attempts to join you into the server you selected (even if you are already in that server).

**To Reproduce**

1.  Enter into buildtheearth.net
2.  Enter `/bt BUILDTEAM` replacing `BUILDTEAM` with any of the build team codes.
3.  Once in the build team server, execute the same command again.
4.  You will be teleported to the build team world map then teleported back to the build team server.

**Expected behavior**
A message should pop up to the player stating that they are already in the server they are trying to connect to.
(This should NOT APPLY if the person is going to a different Sub-Server than what they are already in currently.)

**Minecraft Version:**
 - 1.12.2 (Could be the same method on other versions)

**Comment by noahhusby** [comment]
Fixed.
