### ISSUE TITLE
Advanced Builder role does not remove automatically (discord)

### ISSUE THREAD

**Issue by Kruidnoott** [BuildTheEarth/bte-net-issues#27]
**Describe the bug**
The bot does not remove the advanced builder role automatically.

**To Reproduce**
In a few days, Ignorethebeaver's role will expire (should expire june 2th) and he will still have the role. The other people who expired had their roles removed manually

**Expected behavior**
After three months after receiving the role, it should automatically expire and be removed.

*in the BTE main discord*

**Comment by Nudelsuppe42** [comment]
This Repo and Issues Tab should be used for Network Bugs/Suggestions. But there is a issue about this already for the bot. Thanks for reporting anyways 😃
