### ISSUE TITLE
Can't add people to project

### ISSUE THREAD

**Issue by lovelyfurball88** [BuildTheEarth/bte-net-issues#28]
People can't be added to the project. It says they are added, but they cannot break/place blocks. Relogging doesn't help. It is probably some lingering issue from the 1k event, where the feature was disabled. I have also waited 20-30 minutes to see if it fixes on its own, it doesn't.

Both the project owner and the added player were on Java 1.16.5

**Comment by yyrichy** [comment]
I think this is a Minefact not a BTE.net issue, so you should go to the Minefact discord.

**Comment by lovelyfurball88** [comment]
> 
> 
> I think this is a Minefact not a BTE.net issue, so you should go to the Minefact discord.

Alright sorry, I thought doing /bug in minefact would bring me to a minefact bug report page.
