### ISSUE TITLE
BuildTheEarth.net 9/11 memorials water

### ISSUE THREAD

**Issue by darkknight11608** [BuildTheEarth/bte-net-issues#31]
<img width="959" alt="Captura de ecrã 2021-09-11 231959" src="https://user-images.githubusercontent.com/90532662/132963000-59f937dd-37b4-40a4-8a55-4ff3a621351b.png">
**Describe the bug**
I think the water is not suposed to be like this

**Screenshot**
The water is kinda weird

**Minecraft Version:**
 - Java
 - Minecraft Version (Ex: 1.16.9)

**Comment by Coppertine** [comment]
Not a network issue, this is a Minefact issue. Bring this up to their discord.

**Comment by Nudelsuppe42** [comment]
As Coppertine said, this is not a network related issue, but one for New York City. Please bring it up on the MineFact discord Server ( https://discord.gg/nMJMMBR ).
