### ISSUE TITLE
Remove any Minefact staff on the tablist.

### ISSUE THREAD

**Issue by d3-cent** [BuildTheEarth/bte-net-issues#4]
The argument is that Minefact staff should not be shown as staff cross network as it will confuse new players.

**Comment by MineFact** [comment]
As long as we cant access the permission system of the Build Teams, it's better to at least show players the network staff. If they have questions or problems they can message them and even if the Network Staff cant help them, they can still foward them to the build team staff.
With the BuildTeam plugin which is currently in development we will probably also add a permission system for each build team and then we can remove the staff prefix in the tab list.
