### ISSUE TITLE
/up places glass blocks in the real city

### ISSUE THREAD

**Issue by the-wildguy** [BuildTheEarth/bte-net-issues#41]
**Describe the bug**
doing /up without perms to build in the main city will place a glass block that stays there

**To Reproduce**
do /up without build perms in the main city

**Expected behavior**
i expected just to go up or for it to not work OR for a ghost block to appear

**Screenshots**
![image](https://github.com/BuildTheEarth/bte-net-issues/assets/90672169/5e58298e-f378-4134-85d2-9cf260804788)

**Minecraft Version:**
 - Java
 - 1.20.1

**Additional context**
Im advanced rank (wildthang08)
yes i did this the day before i did this bug to see if it would go away but it didn't, this is not a ghost block nickmoo08 got rid of it for me

**Comment by MineFact** [comment]
Hey, thanks for submitting this issue. It should be fixed on the CityServer and all BuildingServers.
