### ISSUE TITLE
Make tab list tips more general for BTE

### ISSUE THREAD

**Issue by d3-cent** [BuildTheEarth/bte-net-issues#5]
These tips at the top are missleading.. Imagine being a new player on the Benelux server and you see that you can become a builder on the whole network by building 10 buildings.. Obviously you will assume that it means that you have to build 10 buildings on any server, not just the Minefact servers.. (this is just one example, the issue itself is: why are the tips all Minefact related? ) - ElectroYT

**Comment by MineFact** [comment]
dublicate
